#FROM ubuntu:16.04
FROM obiwan/py3:latest

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

COPY obiwan_py3_requirements.txt /tmp/
RUN pip3 install --requirement /tmp/obiwan_py3_requirements.txt
