#FROM ubuntu:16.04
FROM obiwan/legacypipe:latest

# output of which python3
ENV python_exe "/usr/bin/python3"

ENV MYINSTALL=/root/myinstall
ENV MYREPO=/root/myrepo

WORKDIR $MYREPO
RUN wget https://github.com/rmjarvis/tmv/archive/v0.73.tar.gz && \
  tar -xf v0.73.tar.gz && cd tmv-0.73 && \
  scons DEBUG=True FLAGS="-O0" && \
  scons install && \
  cd ../ && rm -rf tmv-0.73

WORKDIR $MYREPO
RUN wget https://github.com/GalSim-developers/GalSim/archive/v1.4.2.tar.gz \
  -O GalSim.tar.gz && tar -xzf GalSim.tar.gz && \
  mv GalSim-1.4.2 GalSim && \
  cd GalSim && \
  scons PYTHON=${python_exe} && \
  scons install && \
  cd ../ && rm -rf $HOME/GalSim
